name: k8s-canary-deployment
image: codefreshplugins/k8s-canary-deployment
tag: 0.1.0
version: 0.1.0
description: Perform canary deployments on a Kubernetes cluster
categories:
- featured
- deployment
keywords:
- kubernetes
- canary
- deployment
sources:
- https://github.com/codefresh-contrib/k8s-canary-deployment
maintainers:
- name: Kostis Kapelonis
  email: ""
icon: https://raw.githubusercontent.com/codefresh-plugins/k8s-canary-deployment/master/icon.jpg
envs:
- name: KUBE_CONTEXT
  type: ""
  description: The name of your cluster (as found in the Codefresh Kubernetes dashboard).
